---
name: 'Validate YAML files'
# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Run yamllint against **all** YAML files in the repository.

on:
  pull_request:
    branches: ['main']
    paths:
      - '**/*.yml'
      - '**/*.yaml'
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'Yamllint'
        uses: 'karancode/yamllint-github-action@v2.1.1'
        with:
          yamllint_file_or_dir: './'
          yamllint_strict: true
          yamllint_comment: true
          yamllint_config_filepath: '.github/workflows/yamllint.conf'
...
